# Generated by Django 3.2.12 on 2022-04-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-data_added']},
        ),
    ]
