# Generated by Django 4.0.3 on 2022-03-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='item',
            new_name='name',
        ),
    ]
